name: reservation
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.9.0
  dio: ^5.3.3
  logger: ^2.0.2+1
  get_storage: ^2.1.1
  flutter_launcher_icons: ^0.13.1
  circular_countdown_timer: ^0.2.3
  flutter_floating_bottom_bar: ^1.2.0
  syncfusion_flutter_charts: ^23.1.43
  syncfusion_flutter_datepicker: ^23.1.43
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter_launcher_icons:
  image_path_android: "assets/images/logo.png"
  image_path_ios: "assets/images/logo.png"
  android: true
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#e0e0e0"
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Graphik
      fonts:
        - asset: assets/fonts/graphik/GraphikBlack.otf
        - asset: assets/fonts/graphik/GraphikBlackItalic.otf
        - asset: assets/fonts/graphik/GraphikBold.otf
        - asset: assets/fonts/graphik/GraphikBoldItalic.otf
        - asset: assets/fonts/graphik/GraphikExtralight.otf
        - asset: assets/fonts/graphik/GraphikExtralightItalic.otf
        - asset: assets/fonts/graphik/GraphikLight.otf
        - asset: assets/fonts/graphik/GraphikLightItalic.otf
        - asset: assets/fonts/graphik/GraphikMedium.otf
        - asset: assets/fonts/graphik/GraphikMediumItalic.otf
        - asset: assets/fonts/graphik/GraphikRegular.otf
        - asset: assets/fonts/graphik/GraphikRegularItalic.otf
        - asset: assets/fonts/graphik/GraphikSemibold.otf
        - asset: assets/fonts/graphik/GraphikSemiboldItalic.otf
        - asset: assets/fonts/graphik/GraphikSuper.otf
        - asset: assets/fonts/graphik/GraphikSuperItalic.otf
        - asset: assets/fonts/graphik/GraphikThin.otf
        - asset: assets/fonts/graphik/GraphikThinItalic.otf
